let gameList = [
    {
        'id': 0,
        'name': "VK Music",
        'imgLink': "img/VK Logo.svg",
        'link': "https://vk.com/audios309444345?section=all",
        'color': "#0077ff",
    },
    {
        'id': 1,
        'name': "Lis-Skins",
        'imgLink': "img/lis.svg",
        'link': "https://lis-skins.ru/",
        'color': "#ff7200",
    },
    {
        'id': 3,
        'name': "СДО",
        'imgLink': "",
        'link': "https://e-learn.petrocollege.ru/",
        'color': "",
    },
    {
        'id': 4,
        'name': "You Tube",
        'imgLink': "img/youtube_social_icon_red.png",
        'link': "https://www.youtube.com/",
        'color': "#FF0000",
    },
    {
        'id': 5,
        'name': "Faciet",
        'imgLink': "img/faciet.webp",
        'link': "https://www.faceit.com/ru/home",
        'color': "#ff5500",
    },
    {
        'id': 9,
        'name': "Faciet Finder",
        'imgLink': "img/faciet.webp",
        'link': "https://faceitfinder.com/",
        'color': "#ff5500",
    },
    {
        'id': 6,
        'name': "Pinterest",
        'imgLink': "img/pint.svg",
        'link': "https://ru.pinterest.com/",
        'color': "#e60023",
    },
    {
        'id': 7,
        'name': "Cybershoke",
        'imgLink': "img/cybershoke.svg",
        'link': "https://cybershoke.net/cs2",
        'color': "#6080ff",
    },
    {
        'id': 8,
        'name': "Яндекс Почта",
        'imgLink': "img/yyy.svg",
        'link': "https://mail.yandex.ru/?ysclid=la865vrsus677224624&uid=854053939#inbox",
        'color': "#fc3f1d",
    },
    {
        'id': 10,
        'name': "Gradient",
        'imgLink': "img/grad.png",
        'link': "https://gradients.app/ru/new",
        'color': "#3e31ba",
    },
    {
        'id': 11,
        'name': "Сбер Онлайн",
        'imgLink': "img/Sberbank_Logo_2020.svg",
        'link': "https://online.sberbank.ru/",
        'color': "#08a652",
    },
    {
        'id': 12,
        'name': "Fonts",
        'imgLink': "img/font.png",
        'link': "https://fonts-online.ru/",
        'color': "#1d1d1d",
    },
    {
        'id': 13,
        'name': "Flaticon",
        'imgLink': "img/flaticon.png",
        'link': "https://www.flaticon.com/",
        'color': "#4ad295",
    },
    {
        'id': 14,
        'name': "Prosettings",
        'imgLink': "img/prosettings-logo.webp",
        'link': "https://prosettings.net/lists/cs2/",
        'color': "#3899d8",
    },
    {
        'id': 15,
        'name': "WT Live",
        'imgLink': "img/wt.png",
        'link': "https://live.warthunder.com/feed/camouflages/",
        'color': "#8d1a1b",
    },
    {
        'id': 16,
        'name': "Gmail",
        'imgLink': "img/gmail-svgrepo-com.svg",
        'link': "https://mail.google.com/mail/u/0/#inbox",
        'color': "#4285f4",
    },
    {
        'id': 17,
        'name': "Twitch",
        'imgLink': "img/1656152266logo-twitch.png",
        'link': "https://www.twitch.tv/",
        'color': "#9f44fe",
    },
    {
        'id': 18,
        'name': "5ka",
        'imgLink': "img/X5_Club_white.png",
        'link': "https://5ka.ru/?ysclid=majuruf8ge901673455",
        'color': "#5faf2d",
    },
    {
        'id': 19,
        'name': "yuPoo",
        'imgLink': "",
        'link': "https://goat-official.x.yupoo.com/albums",
        'color': "",
    },
    {
        'id': 20,
        'name': "info-lan",
        'imgLink': "img/wifi.png",
        'link': "https://stats.info-lan.ru/",
        'color': "#243e90",
    },
    {
        'id': 21,
        'name': "Web tools",
        'imgLink': "",
        'link': "https://webcode.tools/",
        'color': "",
    },
    {
        'id': 22,
        'name': "Git-Hub",
        'imgLink': "img/github-mark-white.png",
        'link': "https://github.com/kodika-dangerlyoha?tab=repositories",
        'color': "#8734fe",
    },
    {
        'id': 23,
        'name': "Автошкола",
        'imgLink': "",
        'link': "https://profteh.com/study/1",
        'color': "",
    },
    {
        'id': 24,
        'name': "ВкусВилл",
        'imgLink': "img/vv.png",
        'link': "https://vkusvill.ru/",
        'color': "#2dbe64",
    },
    {
        'id': 25,
        'name': "SVG Icons",
        'imgLink': "",
        'link': "https://www.svgrepo.com/",
        'color': "",
    },
    {
        'id': 26,
        'name': "Гос Услуги",
        'imgLink': "img/gosuslugi.svg",
        'link': "https://www.gosuslugi.ru/",
        'color': "#FFF",
    },
    {
        'id': 27,
        'name': "Иви",
        'imgLink': "img/ivi.svg",
        'link': "https://www.ivi.ru/",
        'color': "#f30745",
    },
]

// let playlists = [
//     {
//         'id': 0,
//         'name': "viperr",
//         'imgLink': "https://sun9-46.userapi.com/impf/6azmktlis-AilJnQ1u2FjR2pERaE8n6CZJZHCQ/YwaBDJ20cvo.jpg?size=300x300&quality=96&sign=fde1214d308eb2789136a53abcfee4be&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847603",
//     },
//     {
//         'id': 1,
//         'name': "26",
//         'imgLink': "https://sun9-72.userapi.com/impf/4O3DwJ37Vwu2tVzmZNBh0CfyQgTh6OVYBTdUQg/t7hSwZTYKsU.jpg?size=400x400&quality=96&sign=04adfa1d0e8d51b4b456e14fd9ee469a&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847602",
//     },
//     {
//         'id': 2,
//         'name': "25",
//         'imgLink': "https://sun9-23.userapi.com/impf/EmTW6XQlFVg8YYICB-M-Ue_sGgpOhp80Pxjt3g/Oggtp0UjvNI.jpg?size=400x400&quality=96&sign=9d300238365113a8e05bbda036c68c94&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847601",
//     },
//     {
//         'id': 3,
//         'name': "23",
//         'imgLink': "https://sun9-77.userapi.com/impf/eU-9jIvxaOFEyfobZwAvh_e3edmmYldfK76qCw/8wclsJ9IbB0.jpg?size=400x400&quality=96&sign=dfae0589b6025efaff7b911b75fd5860&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847598",
//     },
//     {
//         'id': 4,
//         'name': "kizaru",
//         'imgLink': "https://sun9-29.userapi.com/impf/MbX7EMX_W_XmNzi5u4YiL-ONyrHUZmad_E0thw/2ZVkAxPj5Sg.jpg?size=400x400&quality=96&sign=2128f3dd7371e9afb389735d04c20304&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847520",
//     },
//     {
//         'id': 5,
//         'name': "alblak 52",
//         'imgLink': "https://sun9-35.userapi.com/impf/vRHns_Xc6dvJKzEIA7GXdF9F4HxQUrnQ26RSzA/9YzjjSr9ZsQ.jpg?size=400x400&quality=96&sign=945950d4dbdcb0ddcf432628be616caf&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847589_ed0ce1d126f2598c30",
//     },
//     {
//         'id': 6,
//         'name': "rizza",
//         'imgLink': "https://sun9-10.userapi.com/impf/JKioA_kWxA1xAu6-a68d7f3SuB4Vj7OKDohVQA/p1bpUoWejTo.jpg?size=400x400&quality=96&sign=554d759097bf9abbfc6c51b6156915bc&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847457_bf5f6b96447845a1b6",
//     },
//     {
//         'id': 7,
//         'name': "LILDRUGHILL",
//         'imgLink': "https://sun9-73.userapi.com/impf/t7kOT9WX5fYLpFA_h87Qak3uCfF52HiP8h6JCA/-oB_PRoZYZQ.jpg?size=400x400&quality=96&sign=f193ebf868ebde83c9caeb082f0fc13f&type=audio",
//         'link': "https://vk.com/music/playlist/309444345_84847596_edf539e69e0098a6f2",
//     },
// ]

let audios = [
    {
        'id': 0,
        'name': "2 Грамма В Блант",
        'author': "kizaru",
        'imgLink': "img/audioImg/mas fuerto.jpg",
        'file': "audios/kizaru - Два грамма в блант.mp3",
    },
    {
        'id': 1,
        'name': "CHAINSAW",
        'author': "9mice",
        'imgLink': "img/audioImg/chainsaw.jpg",
        'file': "audios/9mice - CHAINSAW.mp3",
    },
    {
        'id': 2,
        'name': "Младшая сестра",
        'add_name': "(opium remix)",
        'author': "Дора",
        'imgLink': "img/audioImg/mladshaya.jpg",
        'file': "audios/KomaRemix - Младшая сестра - Дора (OPIUM REMIX).mp3",
    },
    {
        'id': 3,
        'name': "Hummer Balenci",
        'add_name': "(Speed up)",
        'author': "Pepel Nahudi",
        'imgLink': "img/audioImg/humerb.png",
        'file': "audios/Pepel Nahudi - Hummer Balenci (Speed up).mp3",
    },
    {
        'id': 4,
        'name': "Порш",
        'author': "OG Buda",
        'imgLink': "img/audioImg/poxwave.png",
        'file': "audios/OG Buda - Порш.mp3",
    },
    {
        'id': 5,
        'name': "Lost Angeles",
        'author': "FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/cristoforocolombo.png",
        'file': "audios/FRIENDLY THUG 52 NGG - Lost Angeles.mp3",
    },
    {
        'id': 6,
        'name': "Early Morning",
        'author': "kizaru",
        'imgLink': "img/audioImg/gremlin.jpg",
        'file': "audios/kizaru - Early Morning.mp3",
    },
    {
        'id': 7,
        'name': "И Я ВЕСЬ ГОРЮ",
        'author': "kizaru",
        'imgLink': "img/audioImg/vesgory.jpg",
        'file': "audios/kizaru - И Я ВЕСЬ ГОРЮ.mp3",
    },
    {
        'id': 8,
        'name': "Зима в сердце",
        'add_name': "(OPIUM REMIX)",
        'author': "Моя Мишель",
        'imgLink': "img/audioImg/zima.jpg",
        'file': "audios/BoGoMoL - Зима в сердце (OPIUM REMIX).mp3",
    },
    {
        'id': 9,
        'name': "Один шаг",
        'add_name': "(prod. by Kreokid, 1eworld)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/DREAMS MONEY CAN BUY.png",
        'file': "audios/Heronwater - Один шаг (prod. by Kreokid, 1eworld).mp3",
    },
    {
        'id': 10,
        'name': "overnight",
        'author': "rizza",
        'imgLink': "img/audioImg/limbo.jpg",
        'file': "audios/rizza - overnight.mp3",
    },
    {
        'id': 11,
        'name': "my mind is broken",
        'author': "rizza",
        'imgLink': "img/audioImg/limbo.jpg",
        'file': "audios/rizza - my mind is broken.mp3",
    },
    {
        'id': 12,
        'name': "Клиффхэнгер",
        'author': "SODA LUV",
        'imgLink': "img/audioImg/NATIVE STRANGERS.png",
        'file': "audios/SODA LUV - Клиффхэнгер.mp3",
    },
    {
        'id': 13,
        'name': "Route 333 OST",
        'author': "PHARAOH",
        'imgLink': "img/audioImg/Million Dollar Depression.png",
        'file': "audios/PHARAOH - Route 333 OST.mp3",
    },
    {
        'id': 14,
        'name': "september",
        'author': "famoukiro & nasvaer",
        'imgLink': "img/audioImg/september.jpg",
        'file': "audios/famoukiro & nasvaer - september.mp3",
    },
    {
        'id': 15,
        'name': "Кровь",
        'author': "Mnogoznaal",
        'imgLink': "img/audioImg/clubbeztancev.jpg",
        'file': "audios/Mnogoznaal - Кровь.mp3",
    },
    {
        'id': 16,
        'name': "BRITNEY",
        'author': "OBLADAET",
        'imgLink': "img/audioImg/britney.png",
        'file': "audios/OBLADAET - BRITNEY.mp3",
    },
    {
        'id': 17,
        'name': "I Am Ready",
        'author': "Blockkid",
        'imgLink': "img/audioImg/Sweet Sixteen.png",
        'file': "audios/Blockkid - I Am Ready.mp3",
    },
    {
        'id': 18,
        'name': "Дал зазу",
        'author': "Блинк",
        'imgLink': "img/audioImg/dalzazu.jpg",
        'file': "audios/Блинк - Дал зазу.mp3",
    },
    {
        'id': 19,
        'name': "Break Up",
        'author': "kizaru",
        'imgLink': "img/audioImg/You Are Loved Where I Am Not.png",
        'file': "audios/kizaru - Break Up.mp3",
    },
    {
        'id': 20,
        'name': "Мне это не нужно",
        'author': "kizaru",
        'imgLink': "img/audioImg/You Are Loved Where I Am Not.png",
        'file': "audios/kizaru - Мне это не нужно.mp3",
    },
    {
        'id': 21,
        'name': "If I Could Teach the World",
        'author': "kizaru",
        'imgLink': "img/audioImg/You Are Loved Where I Am Not.png",
        'file': "audios/kizaru - If I Could Teach the World.mp3",
    },
    {
        'id': 22,
        'name': "Быть со мной",
        'author': "kizaru",
        'imgLink': "img/audioImg/Poison.png",
        'file': "audios/kizaru - Быть со мной.mp3",
    },
    {
        'id': 23,
        'name': "Bentayga",
        'author': "Big Baby Tape",
        'imgLink': "img/audioImg/VARSKVA.png",
        'file': "audios/Big Baby Tape - Bentayga.mp3",
    },
    {
        'id': 24,
        'name': "Benzomageddon",
        'author': "Big Baby Tape",
        'imgLink': "img/audioImg/VARSKVA.png",
        'file': "audios/Big Baby Tape - Benzomageddon.mp3",
    },
    {
        'id': 25,
        'name': "Keys to the City",
        'author': "Big Baby Tape",
        'imgLink': "img/audioImg/VARSKVA.png",
        'file': "audios/Big Baby Tape - Keys to the City.mp3",
    },
    {
        'id': 26,
        'name': "Lo Siento",
        'author': "Big Baby Tape",
        'imgLink': "img/audioImg/VARSKVA.png",
        'file': "audios/Big Baby Tape - Lo Siento.mp3",
    },
    {
        'id': 27,
        'name': "Haunted House",
        'author': "Aarne, Big Baby Tape, kizaru",
        'imgLink': "img/audioImg/AA LANGUAGE 2.png",
        'file': "audios/Aarne, Big Baby Tape, kizaru - Haunted House.mp3",
    },
    {
        'id': 28,
        'name': "amphibian",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/test drive archive.png",
        'file': "audios/LILDRUGHILL - amphibian.mp3",
    },
    {
        'id': 29,
        'name': "burn out",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/test drive archive.png",
        'file': "audios/LILDRUGHILL - burn out.mp3",
    },
    {
        'id': 30,
        'name': "Cardio",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/rEVOLVE.png",
        'file': "audios/LILDRUGHILL - Cardio.mp3",
    },
    {
        'id': 31,
        'name': "Cream (Uh Uh Uh)",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/rEVOLVE.png",
        'file': "audios/LILDRUGHILL - Cream (Uh Uh Uh).mp3",
    },
    {
        'id': 32,
        'name': "Domino",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/rEVOLVE.png",
        'file': "audios/LILDRUGHILL - Domino.mp3",
    },
    {
        'id': 33,
        'name': "cant be alone (j1mmy)",
        'author': "Некромантик",
        'imgLink': "img/audioImg/cantbealone.jpg",
        'file': "audios/Некромантик - cant be alone (j1mmy).mp3",
    },
    {
        'id': 34,
        'name': "Fukashigi no Carte",
        'author': "Bunny Girl Senpai ED",
        'imgLink': "img/audioImg/mai2.jpg",
        'file': "audios/Bunny Girl Senpai ED - Fukashigi no Carte.mp3",
    },
    {
        'id': 35,
        'name': "6 кадров",
        'author': "unki",
        'imgLink': "img/audioImg/JERKSHITHAPPENS.jpg",
        'file': "audios/unki - 6 кадров.mp3",
    },
    {
        'id': 36,
        'name': "Врач",
        'author': "unki",
        'imgLink': "img/audioImg/JERKSHITHAPPENS.jpg",
        'file': "audios/unki - Врач.mp3",
    },
    {
        'id': 37,
        'name': "Штекер",
        'author': "unki",
        'imgLink': "img/audioImg/JERKSHITHAPPENS.jpg",
        'file': "audios/unki - Штекер.mp3",
    },
    {
        'id': 38,
        'name': "Дерьмо",
        'author': "unki",
        'imgLink': "img/audioImg/JERKSHITHAPPENS.jpg",
        'file': "audios/unki - Дерьмо.mp3",
    },
    {
        'id': 39,
        'name': "Jeff the Killer",
        'add_name': "(feat. sly sheen)",
        'author': "unki",
        'imgLink': "img/audioImg/JERKSHITHAPPENS.jpg",
        'file': "audios/unki, sly sheen - Jeff the Killer.mp3",
    },
    {
        'id': 40,
        'name': "Пробки",
        'add_name': "(Prod. by Heronwater)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/ncl.png",
        'file': "audios/Heronwater - Пробки (Prod. by Heronwater).mp3",
    },
    {
        'id': 41,
        'name': "Рок стар ",
        'add_name': "(prod. by stopy, babyboosouljah, Heronwater)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/rockstar.jpg",
        'file': "audios/Heronwater - Рок стар (prod. by stopy, babyboosouljah, Heronwater).mp3",
    },
    {
        'id': 42,
        'name': "Соло",
        'add_name': "(feat. BUSHIDO ZHO) (Prod. by Heronwater)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/DREAMS MONEY CAN BUY.png",
        'file': "audios/Heronwater, BUSHIDO ZHO - Соло (prod. by Heronwater, owleeng).mp3",
    },
    {
        'id': 43,
        'name': "СЕЙЧАС",
        'author': "NEWLIGHTCHILD",
        'imgLink': "img/audioImg/IN MY DNA.jpg",
        'file': "audios/NEWLIGHTCHILD - СЕЙЧАС.mp3",
    },
    {
        'id': 44,
        'name': "Paranoia",
        'add_name': "(feat. FRESCO)",
        'author': "ROCKET",
        'imgLink': "img/audioImg/Ego Trippin.png",
        'file': "audios/ROCKET feat. FRESCO - Paranoia.mp3",
    },
    {
        'id': 45,
        'name': "More",
        'author': "ROCKET",
        'imgLink': "img/audioImg/Ego Trippin.png",
        'file': "audios/ROCKET - More.mp3",
    },
    {
        'id': 46,
        'name': "Karma",
        'author': "LILDRUGHILL",
        'imgLink': "img/audioImg/glow.png",
        'file': "audios/LILDRUGHILL - Karma.mp3",
    },
    {
        'id': 47,
        'name': "Беспредел.ru",
        'author': "ICEGERGERT",
        'imgLink': "img/audioImg/opri4niki.png",
        'file': "audios/ICEGERGERT - Беспредел.ru (Prod. by Lauren).mp3",
    },
    {
        'id': 48,
        'name': "Say What's Real Freestyle",
        'add_name': "(prod. by Wex, Weightonme, Heronwater)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/4mws.png",
        'file': "audios/Heronwater - Say What's Real Freestyle (prod. by Wex, Weightonme, Heronwater).mp3",
    },
    {
        'id': 49,
        'name': "Не нужна",
        'add_name': "(prod. by Heronwater, twomollyincup, fxcksenseless)",
        'author': "Heronwater",
        'imgLink': "img/audioImg/4mws.png",
        'file': "audios/Heronwater - Не нужна (prod. by Heronwater, twomollyincup, fxcksenseless).mp3",
    },
    {
        'id': 50,
        'name': "Выключатель",
        'author': "163ONMYNECK",
        'imgLink': "img/audioImg/NO OFFENCE.png",
        'file': "audios/163ONMYNECK - Выключатель.mp3",
    },
    {
        'id': 51,
        'name': "Стоматологичка",
        'author': "163ONMYNECK",
        'add_name': "feat. BUSHIDO ZHO",
        'imgLink': "img/audioImg/NO OFFENCE.png",
        'file': "audios/163ONMYNECK feat. BUSHIDO ZHO - Стоматологичка.mp3",
    },
    {
        'id': 52,
        'name': "2015",
        'author': "Whole Lotta Swag",
        'imgLink': "img/audioImg/FiRMA Flo.jpg",
        'file': "audios/Whole Lotta Swag - 2015 (3).mp3",
    },
    {
        'id': 53,
        'name': "Некогда мечтать",
        'author': "Скриптонит, FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/Fantasy Mixtape.png",
        'file': "audios/Скриптонит, FRIENDLY THUG 52 NGG - Некогда мечтать.mp3",
    },
    {
        'id': 54,
        'name': "грусть",
        'author': "rizza",
        'imgLink': "img/audioImg/madness of the abyss.png",
        'file': "audios/rizza - грусть.mp3",
    },
    {
        'id': 55,
        'name': "полнолуние",
        'author': "rizza",
        'imgLink': "img/audioImg/madness of the abyss.png",
        'file': "audios/rizza - полнолуние.mp3",
    },
    {
        'id': 56,
        'name': "настоящий",
        'author': "rizza",
        'imgLink': "img/audioImg/madness of the abyss.png",
        'file': "audios/rizza - настоящий.mp3",
    },
    {
        'id': 57,
        'name': "No Gletcher Gang",
        'author': "FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/cristoforocolombo.png",
        'file': "audios/FRIENDLY THUG 52 NGG - No Gletcher Gang.mp3",
    },
    {
        'id': 58,
        'name': "After Paper Flow",
        'author': "FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/cristoforocolombo.png",
        'file': "audios/FRIENDLY THUG 52 NGG - After Paper Flow.mp3",
    },
    {
        'id': 59,
        'name': "October",
        'author': "FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/cristoforocolombo.png",
        'file': "audios/FRIENDLY THUG 52 NGG - October.mp3",
    },
    {
        'id': 60,
        'name': "Sladki Snov Rapper 2",
        'author': "FRIENDLY THUG 52 NGG",
        'imgLink': "img/audioImg/cristoforocolombo.png",
        'file': "audios/FRIENDLY THUG 52 NGG - Sladki Snov Rapper 2.mp3",
    },
    {
        'id': 61,
        'name': "Сваровски",
        'author': "Heronwater",
        'imgLink': "img/audioImg/swarovski.jpg",
        'file': "audios/Heronwater - Сваровски.mp3",
    },
    {
        'id': 62,
        'name': "Сияешь 934-8777",
        'author': "Heronwater",
        'imgLink': "img/audioImg/ODYSSEY.png",
        'file': "audios/Heronwater - Сияешь 934-8777.mp3",
    },
    {
        'id': 63,
        'name': "До замка",
        'author': "Heronwater",
        'imgLink': "img/audioImg/ODYSSEY.png",
        'file': "audios/Heronwater - До замка.mp3",
    },
    {
        'id': 64,
        'name': "Хэллоу Китти",
        'author': "uglystephan",
        'imgLink': "img/audioImg/helloKity.jpg",
        'file': "audios/uglystephan - Хэллоу Китти.mp3",
    },
    {
        'id': 65,
        'name': "Midnight Blues",
        'author': "kizaru",
        'add_name': "feat. Big Moochie Grape",
        'imgLink': "img/audioImg/midnightBlues.jpg",
        'file': "audios/kizaru feat. Big Moochie Grape - Midnight Blues.mp3",
    },
    {
        'id': 66,
        'name': "ХП",
        'author': "Boulevard Depo",
        'imgLink': "img/audioImg/hp.jpg",
        'file': "audios/Boulevard Depo - ХП.mp3",
    },
    {
        'id': 67,
        'name': "Аритмия",
        'author': "ICEGERGERT",
        'add_name': "prod. by giovani, Frontyard",
        'imgLink': "img/audioImg/ave.jpg",
        'file': "audios/ICEGERGERT - Аритмия (prod by giovani, Frontyard).mp3",
    },
    {
        'id': 68,
        'name': "Casino",
        'author': "ICEGERGERT",
        'add_name': "prod. by eightlone",
        'imgLink': "img/audioImg/ave.jpg",
        'file': "audios/ICEGERGERT - Casino (prod by eightlone).mp3",
    },
    {
        'id': 69,
        'name': "Amsterdam",
        'author': "ICEGERGERT",
        'add_name': "prod. by faw rifa, karnicero",
        'imgLink': "img/audioImg/ave.jpg",
        'file': "audios/ICEGERGERT - Amsterdam (prod by faw rifa, karnicero).mp3",
    },
    {
        'id': 70,
        'name': "Чемпионы",
        'author': "Polyana, OG Buda, MAYOT, молодой калуга, 163ONMYNECK",
        'imgLink': "img/audioImg/champion.jpg",
        'file': "audios/Polyana, OG Buda, MAYOT, молодой калуга, 163ONMYNECK - Чемпионы (prod. by KOOKY).mp3",
    },
    {
        'id': 71,
        'name': "На Рожке и На Мне",
        'author': "OG Buda",
        'add_name': "prod. by revvboy & chasershawty",
        'imgLink': "img/audioImg/fr3.png",
        'file': "audios/OG Buda - На Рожке и На Мне (prod. by revvboy & chasershawty).mp3",
    },
    {
        'id': 72,
        'name': "Забудь",
        'author': "Guram D, Toxi$",
        'imgLink': "img/audioImg/zabud.jpg",
        'file': "audios/Guram D, Toxi$ - Забудь.mp3",
    },
    {
        'id': 73,
        'name': "VICTIM",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - VICTIM.mp3",
    },
    {
        'id': 74,
        'name': "SLAYERR",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - SLAYERR.mp3",
    },
    {
        'id': 75,
        'name': "BAD BITCHES ONLY",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - BAD BITCHES ONLY.mp3",
    },
    {
        'id': 76,
        'name': "1-800-PARADISE",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - 1-800-PARADISE.mp3",
    },
    {
        'id': 77,
        'name': "HILLS",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - HILLS.mp3",
    },
    {
        'id': 78,
        'name': "ХОЛОД",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/godsystem.jpg",
        'file': "audios/Kai Angel - ХОЛОД.mp3",
    },
    {
        'id': 79,
        'name': "40",
        'author': "rizza",
        'imgLink': "img/audioImg/40.jpg",
        'file': "audios/rizza - 40.mp3",
    },
    {
        'id': 80,
        'name': "Сегодня",
        'author': "xxxmanera",
        'imgLink': "img/audioImg/segod.jpg",
        'file': "audios/xxxmanera - Сегодня.mp3",
    },
    {
        'id': 81,
        'name': "Madam",
        'author': "Kai Angel",
        'imgLink': "img/audioImg/madam.jpg",
        'file': "audios/Kai Angel - Madam.mp3",
    },
    {
        'id': 82,
        'name': "ROVVER",
        'author': "smazzi",
        'imgLink': "img/audioImg/rovver.jpg",
        'file': "audios/smazzi - ROVVER.mp3",
    },
    {
        'id': 83,
        'name': "Hummer Balenci",
        'author': "Pepel Nahudi",
        'imgLink': "img/audioImg/humerb.png",
        'file': "audios/Pepel Nahudi - Hummer Balenci.mp3",
    },
    {
        'id': 84,
        'name': "RaNDoMizer ",
        'author': "OG Buda",
        'add_name': "prod. by revvboy & Dlsshhhh",
        'imgLink': "img/audioImg/szn.jpg",
        'file': "audios/OG Buda - RaNDoMizer (prod. by revvboy & Dlsshhhh).mp3",
    },
    {
        'id': 85,
        'name': "Flow",
        'author': "молодой калуга",
        'add_name': "",
        'imgLink': "img/audioImg/blockseason.jpg",
        'file': "audios/молодой калуга - Flow.mp3",
    },
    {
        'id': 86,
        'name':  "Темнота",
        'author':  "молодой калуга",
        'add_name':  "",
        'imgLink':  "img/audioImg/blockseason.jpg",
        'file':  "audios/молодой калуга - Темнота.mp3",
    },
    {
        'id': 87,
        'name':  "Сам Себе Отвратителен",
        'author':  "OG Buda",
        'add_name':  "prod. by roxstrboy & salean & t9xnickk",
        'imgLink':  "img/audioImg/szn.jpg",
        'file':  "audios/OG Buda - Сам Себе Отвратителен (prod. by roxstrboy & salean & t9xnickk).mp3",
    },
    {
        'id': 88,
        'name':  "Не Получаеца((",
        'author':  "OG Buda",
        'add_name':  "prod. by DJ Chuk & SSi",
        'imgLink':  "img/audioImg/szn.jpg",
        'file':  "audios/OG Buda - Не Получаеца(( (prod. by DJ Chuk & SSi).mp3",
    },
    {
        'id': 89,
        'name':  "Помешан",
        'author':  "xe1to feat. BLESSQ",
        'add_name':  "",
        'imgLink':  "img/audioImg/pomeshan.jpg",
        'file':  "audios/xe1to feat. BLESSQ - Помешан.mp3",
    },
    {
        'id': 90,
        'name':  "Водка 2",
        'author':  "Джон Гарик",
        'add_name':  "",
        'imgLink':  "img/audioImg/fclass.jpg",
        'file':  "audios/Джон Гарик - Водка 2.mp3",
    },
    {
        'id': 91,
        'name': "Классика",
        'author': "Джон Гарик, Baby Melo",
        'add_name': "",
        'imgLink': "img/audioImg/fclass.jpg",
        'file': "audios/Джон Гарик, Baby Melo - Классика.mp3",
    },
    {
        'id': 92,
        'name':  "Три года назад",
        'author':  "Джон Гарик",
        'add_name':  "",
        'imgLink':  "img/audioImg/fclass.jpg",
        'file':  "audios/Джон Гарик - Три года назад.mp3",
    },
    {
        'id': 93,
        'name':  "Плюшки",
        'author':  "Polyana",
        'add_name':  "",
        'imgLink':  "img/audioImg/proshu.png",
        'file':  "audios/Polyana - Плюшки.mp3",
    },
    {
        'id': 94,
        'name':  "Многознаал",
        'author':  "Polyana",
        'add_name':  "",
        'imgLink':  "img/audioImg/proshu.png",
        'file':  "audios/Polyana - Многознаал.mp3",
    },
    {
        'id': 95,
        'name':  "Цели",
        'author':  "молодой калуга",
        'add_name':  "",
        'imgLink':  "img/audioImg/blockseason.jpg",
        'file':  "audios/молодой калуга - Цели.mp3",
    },
    {
        'id': 96,
        'name':  "Young thug",
        'author':  "молодой калуга",
        'add_name':  "",
        'imgLink':  "img/audioImg/blockseason.jpg",
        'file':  "audios/молодой калуга - Young thug.mp3",
    },
    {
        'id': 97,
        'name':  "Сломана",
        'author':  "Baby Melo",
        'add_name':  "",
        'imgLink':  "img/audioImg/slomana.jpg",
        'file':  "audios/Baby Melo, FADE031 - Сломана.mp3",
    },
    {
        'id': 98,
        'name':  "feaR2",
        'author':  "PINQ",
        'add_name':  "",
        'imgLink':  "img/audioImg/fear2.jpg",
        'file':  "audios/PINQ - feaR2.mp3",
    },
    {
        'id': 99,
        'name':  "Привет",
        'author':  "Kambulat",
        'add_name':  "",
        'imgLink':  "img/audioImg/kamb.png",
        'file':  "audios/Kambulat - Привет.mp3",
    },
    {
        'id': 100,
        'name':  "Осколок",
        'author':  "OBLADAET",
        'add_name':  "",
        'imgLink':  "img/audioImg/735.jpg",
        'file':  "audios/OBLADAET - Осколок.mp3",
    },
    {
        'id': 101,
        'name':  "FAIRYTALE",
        'author':  "OBLADAET",
        'add_name':  "",
        'imgLink':  "img/audioImg/735.jpg",
        'file':  "audios/OBLADAET - FAIRYTALE.mp3",
    },
    {
        'id': 102,
        'name':  "GTA",
        'author':  "OBLADAET",
        'add_name':  "",
        'imgLink':  "img/audioImg/735.jpg",
        'file':  "audios/OBLADAET - GTA.mp3",
    },
    {
        'id': 103,
        'name':  "ONE CALL",
        'author':  "Pepel Nahudi",
        'add_name':  "",
        'imgLink':  "img/audioImg/autumn.png",
        'file':  "audios/Pepel Nahudi - ONE CALL.mp3",
    },
    {
        'id': 104,
        'name':  "HUYOMAYO",
        'author':  "Pepel Nahudi",
        'add_name':  "",
        'imgLink':  "img/audioImg/autumn.png",
        'file':  "audios/Pepel Nahudi - HUYOMAYO.mp3",
    },
    {
        'id': 105,
        'name':  "AUDIODRUG",
        'author':  "Pepel Nahudi",
        'add_name':  "",
        'imgLink':  "img/audioImg/psyhlove.jpg",
        'file':  "audios/Pepel Nahudi - AUDIODRUG.mp3",
    },
    {
        'id': 106,
        'name':  "Земля",
        'author':  "Маша и Медведи",
        'add_name':  "(Remix Dissynursum)",
        'imgLink':  "img/audioImg/zem1.jpg",
        'file':  "audios/Маша и Медведи - Земля (Remix Dissynursum).mp3",
    },
    {
        'id': 107,
        'name':  "Ocean",
        'author':  "Hugo Loud",
        'add_name':  "(prod. Elementry)",
        'imgLink':  "img/audioImg/ocean.png",
        'file':  "audios/Hugo Loud - Ocean (prod. Elementry).mp3",
    },
    {
        'id': 108,
        'name':  "varvara",
        'author':  "Beliwhatt",
        'add_name':  "",
        'imgLink':  "img/audioImg/designing.jpg",
        'file':  "audios/Beliwhatt - varvara.mp3",
    },
    {
        'id': 109,
        'name':  "i do know",
        'author':  "Beliwhatt",
        'add_name':  "",
        'imgLink':  "img/audioImg/ELEVEN SUFFERINGS.jpg",
        'file':  "audios/Beliwhatt - i do know.mp3",
    },
    {
        'id': 110,
        'name':  "под мостом",
        'author':  "Beliwhatt",
        'add_name':  "",
        'imgLink':  "img/audioImg/ELEVEN SUFFERINGS.jpg",
        'file':  "audios/Beliwhatt - под мостом.mp3",
    },
    {
        'id': 111,
        'name':  "slim bitch",
        'author':  "Beliwhatt",
        'add_name':  "",
        'imgLink':  "img/audioImg/ELEVEN SUFFERINGS.jpg",
        'file':  "audios/Beliwhatt - slim bitch.mp3",
    },
    {
        'id': 112,
        'name':  "море",
        'author':  "Beliwhatt",
        'add_name':  "",
        'imgLink':  "img/audioImg/ELEVEN SUFFERINGS.jpg",
        'file':  "audios/Beliwhatt - море.mp3",
    },
    {
        'id': 113,
        'name':  "Гостиница Космос",
        'author':  "Mnogoznaal",
        'add_name':  "",
        'imgLink':  "img/audioImg/Hotel Cosmos.png",
        'file':  "audios/Mnogoznaal - Гостиница Космос.mp3",
    },
    {
        'id': 114,
        'name':  "Минус 40",
        'author':  "Mnogoznaal",
        'add_name':  "",
        'imgLink':  "img/audioImg/Hotel Cosmos.png",
        'file':  "audios/Mnogoznaal - Минус 40.mp3",
    },
    {
        'id': 115,
        'name':  "Ветра",
        'author':  "Mnogoznaal",
        'add_name':  "",
        'imgLink':  "img/audioImg/Circle Of Winds.png",
        'file':  "audios/Mnogoznaal - Ветра.mp3",
    },
    {
        'id': 116,
        'name':  "Дуга",
        'author':  "Mnogoznaal",
        'add_name':  "",
        'imgLink':  "img/audioImg/Circle Of Winds.png",
        'file':  "audios/Mnogoznaal - Дуга.mp3",
    },
    {
        'id': 117,
        'name':  "Антигерой",
        'author':  "Mnogoznaal",
        'add_name':  "",
        'imgLink':  "img/audioImg/Circle Of Winds.png",
        'file':  "audios/Mnogoznaal - Антигерой.mp3",
    },
    {
        'id': 118,
        'name':  "Jersey Luv",
        'author':  "kizaru",
        'add_name':  "",
        'imgLink':  "img/audioImg/jersey luv.jpg",
        'file':  "audios/kizaru - Jersey Luv.mp3",
    },
    {
        'id': 119,
        'name':  "Деталь",
        'author':  "3TERNITY",
        'add_name':  "",
        'imgLink':  "img/audioImg/SENSE R3MELT.png",
        'file':  "audios/3TERNITY - Деталь.mp3",
    },
    {
        'id': 120,
        'name':  "Минерал",
        'author':  "3TERNITY",
        'add_name':  "",
        'imgLink':  "img/audioImg/SENSE R3MELT.png",
        'file':  "audios/3TERNITY - Минерал.mp3",
    },
    {
        'id': 121,
        'name':  "РЕВНУЮ",
        'author':  "BUSHIDO ZHO",
        'add_name':  "(Aarne, Liza Evans)",
        'imgLink':  "img/audioImg/WE LIVE ONLY ONCE.png",
        'file':  "audios/Aarne, BUSHIDO ZHO, Liza Evans - РЕВНУЮ.mp3",
    },
    {
        'id': 122,
        'name':  "далеко (большой Бушизм)",
        'author':  "BUSHIDO ZHO",
        'add_name':  "(prod. by wex & heysubr)",
        'imgLink':  "img/audioImg/daleko.jpg",
        'file':  "audios/BUSHIDO ZHO - далеко (большой Бушизм) (prod. by wex & heysubr).mp3",
    },
]

let authors = [
    {
        'id': 0,
        'name': "kizaru",
        'imgLink': "img/authros/kizaru.jpg",
        'banner_link': "img/authros/banners/kizaru.jpg",
    },
    {
        'id': 1,
        'name': "rizza",
        'imgLink': "img/authros/rizza.jpg",
        'banner_link': "img/authros/banners/rizza.jpg",
    },
    {
        'id': 2,
        'name': "Big Baby Tape",
        'imgLink': "img/authros/Big Baby Tape.jpg",
        'banner_link': "img/authros/banners/bbt.jpg",
    },
    {
        'id': 3,
        'name': "LILDRUGHILL",
        'imgLink': "img/authros/lildrughill.jpg",
        'banner_link': "",
    },
    {
        'id': 4,
        'name': "Kai Angel",
        'imgLink': "img/authros/kai.jpg",
        'banner_link': "",
    },
    {
        'id': 5,
        'name': "OBLADAET",
        'imgLink': "img/authros/obladaet.jpg",
        'banner_link': "img/authros/banners/obla.jpg",
    },
]